### PR TITLE
#69 set request code in build

### PR DESCRIPTION
**Pull request by arnaud33200**
This is my pull request for the issue #69 

* setup the requestCode in the builder (both image and video)
* update the example app to test the custom request code

### CODE REVIEW

**Comment by alhazmy13** [comment]
Thanks @arnaud33200 
[Version 2.4.4](https://github.com/alhazmy13/MediaPicker/releases/tag/2.4.4) is out

**Comment by arnaud33200** [comment]
it's funny I don't see it ... did you remove it?

**Comment by Aroniez** [comment]
Apparently I'm not seeing it either and I'm using 2.4.4.

**Comment by alhazmy13** [comment]
How so! 
https://bintray.com/alhazmy13/maven/MediaPicker/2.4.4

**Comment by Aroniez** [comment]
The method I'm looking for in 2.4.4 version is `.requestCode(CUSTOM_REQUEST_CODE)`

**Comment by Aroniez** [comment]
I think the issue was that the changes were merged to develop `branch `and were not eventually merged to `master`

**Pull request merged**
